In [28]:
import pandas as pd
import numpy as np
import pickle
import json
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV

In [2]:
original_df=pd.read_csv("heart.csv")
original_df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
original_df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [6]:
original_x=original_df.drop('target',axis=1)
original_y=original_df['target']

### normalization

In [9]:
norm_scaler=MinMaxScaler()
arr1=norm_scaler.fit_transform(original_x)
norm_df=pd.DataFrame(arr1,columns=original_x.columns)
norm_df

age  sex        cp  trestbps      chol  fbs  restecg   thalach  \
0    0.708333  1.0  1.000000  0.481132  0.244292  1.0      0.0  0.603053   
1    0.166667  1.0  0.666667  0.339623  0.283105  0.0      0.5  0.885496   
2    0.250000  0.0  0.333333  0.339623  0.178082  0.0      0.0  0.770992   
3    0.562500  1.0  0.333333  0.245283  0.251142  0.0      0.5  0.816794   
4    0.583333  0.0  0.000000  0.245283  0.520548  0.0      0.5  0.702290   
..        ...  ...       ...       ...       ...  ...      ...       ...   
298  0.583333  0.0  0.000000  0.433962  0.262557  0.0      0.5  0.396947   
299  0.333333  1.0  1.000000  0.150943  0.315068  0.0      0.5  0.465649   
300  0.812500  1.0  0.000000  0.471698  0.152968  1.0      0.5  0.534351   
301  0.583333  1.0  0.000000  0.339623  0.011416  0.0      0.5  0.335878   
302  0.583333  0.0  0.333333  0.339623  0.251142  0.0      0.0  0.786260   

     exang   oldpeak  slope    ca      thal  
0      0.0  0.370968    0.0  0.00  0.333333  
1      0.0  0.564516    0.0  0.00  0.666667  
2      0.0  0.225806    1.0  0.00  0.666667  
3      0.0  0.129032    1.0  0.00  0.666667  
4      1.0  0.096774    1.0  0.00  0.666667  
..     ...       ...    ...   ...       ...  
298    1.0  0.032258    0.5  0.00  1.000000  
299    0.0  0.193548    0.5  0.00  1.000000  
300    0.0  0.548387    0.5  0.50  1.000000  
301    1.0  0.193548    0.5  0.25  1.000000  
302    0.0  0.000000    0.5  0.25  0.666667  

[303 rows x 13 columns]

In [10]:
norm_df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528465    0.683168    0.322332    0.354941    0.274575    0.148515   
std      0.189210    0.466011    0.344017    0.165454    0.118335    0.356198   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.385417    0.000000    0.000000    0.245283    0.194064    0.000000   
50%      0.541667    1.000000    0.333333    0.339623    0.260274    0.000000   
75%      0.666667    1.000000    0.666667    0.433962    0.339041    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.264026    0.600358    0.326733    0.167678    0.699670    0.182343   
std      0.262930    0.174849    0.469794    0.187270    0.308113    0.255652   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.477099    0.000000    0.000000    0.500000    0.000000   
50%      0.500000    0.625954    0.000000    0.129032    0.500000    0.000000   
75%      0.500000    0.725191    1.000000    0.258065    1.000000    0.250000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

             thal  
count  303.000000  
mean     0.771177  
std      0.204092  
min      0.000000  
25%      0.666667  
50%      0.666667  
75%      1.000000  
max      1.000000

In [12]:
x_norm=norm_df


In [13]:
x_train,x_test,y_train,y_test=train_test_split(x_norm,y,test_size=0.2,random_state=16,stratify=y)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [14]:
norm_model=KNeighborsClassifier(n_neighbors=5,p=2)
norm_model.fit(x_train,y_train)

KNeighborsClassifier()

In [16]:
def model_eval(model,x,y):
    y_pred=model.predict(x)
    acc=accuracy_score(y,y_pred)
    con_mat=confusion_matrix(y,y_pred)
    cl_report=classification_report(y,y_pred)
    
    print(f"accuracy score : {acc}")
    print(f"confusion matrix : \n{con_mat}")
    print(f"classification report : \n{cl_report}")
    
model_eval(norm_model,x_train,y_train)      # training
    

accuracy score : 0.859504132231405
confusion matrix : 
[[ 91  19]
 [ 15 117]]
classification report : 
              precision    recall  f1-score   support

           0       0.86      0.83      0.84       110
           1       0.86      0.89      0.87       132

    accuracy                           0.86       242
   macro avg       0.86      0.86      0.86       242
weighted avg       0.86      0.86      0.86       242



In [17]:
# testing
model_eval(norm_model,x_test,y_test)

accuracy score : 0.819672131147541
confusion matrix : 
[[21  7]
 [ 4 29]]
classification report : 
              precision    recall  f1-score   support

           0       0.84      0.75      0.79        28
           1       0.81      0.88      0.84        33

    accuracy                           0.82        61
   macro avg       0.82      0.81      0.82        61
weighted avg       0.82      0.82      0.82        61



### standaradization

In [18]:
original_df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [48]:
std_scaler=StandardScaler()
arr2=std_scaler.fit_transform(original_x)
std_df=pd.DataFrame(arr2,columns=original_x.columns)
x_std=std_df
x_std

age       sex        cp  trestbps      chol       fbs   restecg  \
0    0.952197  0.681005  1.973123  0.763956 -0.256334  2.394438 -1.005832   
1   -1.915313  0.681005  1.002577 -0.092738  0.072199 -0.417635  0.898962   
2   -1.474158 -1.468418  0.032031 -0.092738 -0.816773 -0.417635 -1.005832   
3    0.180175  0.681005  0.032031 -0.663867 -0.198357 -0.417635  0.898962   
4    0.290464 -1.468418 -0.938515 -0.663867  2.082050 -0.417635  0.898962   
..        ...       ...       ...       ...       ...       ...       ...   
298  0.290464 -1.468418 -0.938515  0.478391 -0.101730 -0.417635  0.898962   
299 -1.033002  0.681005  1.973123 -1.234996  0.342756 -0.417635  0.898962   
300  1.503641  0.681005 -0.938515  0.706843 -1.029353  2.394438  0.898962   
301  0.290464  0.681005 -0.938515 -0.092738 -2.227533 -0.417635  0.898962   
302  0.290464 -1.468418  0.032031 -0.092738 -0.198357 -0.417635 -1.005832   

      thalach     exang   oldpeak     slope        ca      thal  
0    0.015443 -0.696631  1.087338 -2.274579 -0.714429 -2.148873  
1    1.633471 -0.696631  2.122573 -2.274579 -0.714429 -0.512922  
2    0.977514 -0.696631  0.310912  0.976352 -0.714429 -0.512922  
3    1.239897 -0.696631 -0.206705  0.976352 -0.714429 -0.512922  
4    0.583939  1.435481 -0.379244  0.976352 -0.714429 -0.512922  
..        ...       ...       ...       ...       ...       ...  
298 -1.165281  1.435481 -0.724323 -0.649113 -0.714429  1.123029  
299 -0.771706 -0.696631  0.138373 -0.649113 -0.714429  1.123029  
300 -0.378132 -0.696631  2.036303 -0.649113  1.244593  1.123029  
301 -1.515125  1.435481  0.138373 -0.649113  0.265082  1.123029  
302  1.064975 -0.696631 -0.896862 -0.649113  0.265082 -0.512922  

[303 rows x 13 columns]

In [49]:
x_train,x_test,y_train,y_test=train_test_split(x_std,y,test_size=0.2,random_state=16,stratify=y)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [50]:
std_model=KNeighborsClassifier(n_neighbors=5,p=2)
std_model.fit(x_train,y_train)

KNeighborsClassifier()

In [51]:
# training
model_eval(std_model,x_train,y_train)

accuracy score : 0.8801652892561983
confusion matrix : 
[[ 93  17]
 [ 12 120]]
classification report : 
              precision    recall  f1-score   support

           0       0.89      0.85      0.87       110
           1       0.88      0.91      0.89       132

    accuracy                           0.88       242
   macro avg       0.88      0.88      0.88       242
weighted avg       0.88      0.88      0.88       242



In [52]:
# testing
model_eval(std_model,x_test,y_test)

accuracy score : 0.819672131147541
confusion matrix : 
[[20  8]
 [ 3 30]]
classification report : 
              precision    recall  f1-score   support

           0       0.87      0.71      0.78        28
           1       0.79      0.91      0.85        33

    accuracy                           0.82        61
   macro avg       0.83      0.81      0.81        61
weighted avg       0.83      0.82      0.82        61



### hyperparameter tuning

#### gridsearchcv

In [29]:
 hyp={'n_neighbors':np.arange(2,20),
      "p":[1,2]}

In [33]:
gscv=GridSearchCV(std_model,hyp)
gscv.fit(x_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19]),
                         'p': [1, 2]})

In [34]:
gscv.best_params_

{'n_neighbors': 16, 'p': 1}

In [35]:
gscv.best_estimator_

KNeighborsClassifier(n_neighbors=16, p=1)

In [ ]:
# after finding out the best params training the model again

In [36]:
std_model_gscv=KNeighborsClassifier(n_neighbors=16,p=1)
std_model_gscv.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=16, p=1)

In [37]:
model_eval(std_model_gscv,x_train,y_train)

accuracy score : 0.8471074380165289
confusion matrix : 
[[ 84  26]
 [ 11 121]]
classification report : 
              precision    recall  f1-score   support

           0       0.88      0.76      0.82       110
           1       0.82      0.92      0.87       132

    accuracy                           0.85       242
   macro avg       0.85      0.84      0.84       242
weighted avg       0.85      0.85      0.85       242



In [38]:
model_eval(std_model_gscv,x_test,y_test)

accuracy score : 0.8688524590163934
confusion matrix : 
[[23  5]
 [ 3 30]]
classification report : 
              precision    recall  f1-score   support

           0       0.88      0.82      0.85        28
           1       0.86      0.91      0.88        33

    accuracy                           0.87        61
   macro avg       0.87      0.87      0.87        61
weighted avg       0.87      0.87      0.87        61



#### RandomizedSearchCV

In [39]:
rscv=RandomizedSearchCV(std_model,hyp)
rscv.fit(x_train,y_train)

RandomizedSearchCV(estimator=KNeighborsClassifier(),
                   param_distributions={'n_neighbors': array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19]),
                                        'p': [1, 2]})

In [40]:
rscv.best_params_

{'p': 2, 'n_neighbors': 6}

In [41]:
rscv.best_estimator_

KNeighborsClassifier(n_neighbors=6)

In [ ]:
# after finding out the best params training the model again

In [53]:
std_model_rscv=KNeighborsClassifier(n_neighbors=6,p=2)
std_model_rscv.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=6)

In [54]:
# training
model_eval(std_model_rscv,x_train,y_train)

accuracy score : 0.871900826446281
confusion matrix : 
[[ 95  15]
 [ 16 116]]
classification report : 
              precision    recall  f1-score   support

           0       0.86      0.86      0.86       110
           1       0.89      0.88      0.88       132

    accuracy                           0.87       242
   macro avg       0.87      0.87      0.87       242
weighted avg       0.87      0.87      0.87       242



In [55]:
# testing
model_eval(std_model_rscv,x_test,y_test)

accuracy score : 0.8524590163934426
confusion matrix : 
[[23  5]
 [ 4 29]]
classification report : 
              precision    recall  f1-score   support

           0       0.85      0.82      0.84        28
           1       0.85      0.88      0.87        33

    accuracy                           0.85        61
   macro avg       0.85      0.85      0.85        61
weighted avg       0.85      0.85      0.85        61



#### final evaluation

In [ ]:
# training 0.87
# testing  0.85


In [57]:
with open("std_model.pkl",'wb')as file:
    pickle.dump(std_model_rscv,file)

In [58]:
with open("std_scaler.pkl",'wb')as file:
    pickle.dump(std_scaler,file)